(source gnu)
(source melpa)

;; global
(depends-on "key-combo")
(depends-on "direx")
(depends-on "wgrep")
(depends-on "auto-save-buffers-enhanced")
(depends-on "autopair")
(depends-on "popwin")
(depends-on "recentf-ext")
(depends-on "sequential-command")
(depends-on "undo-tree")
(depends-on "yasnippet")
(depends-on "auto-complete")
(depends-on "helm")
(depends-on "magit")
(depends-on "migemo")

;; by language
(depends-on "emmet-mode") ;; zencodingの後継

(depends-on "ruby-mode")
(depends-on "inf-ruby")
(depends-on "ruby-end")
(depends-on "ruby-block")
(depends-on "coffee-mode")
(depends-on "haml-mode")
(depends-on "sws-mode")
(depends-on "sass-mode")
(depends-on "stylus-mode")
(depends-on "yaml-mode")

(depends-on "go-mode")

(depends-on "php-mode")
