(source gnu)
(source melpa)

;; global
(depends-on "init-loader")
(depends-on "key-combo")
(depends-on "direx")
(depends-on "wgrep")
(depends-on "auto-save-buffers-enhanced")
(depends-on "autopair")
(depends-on "popwin")
(depends-on "recentf-ext")
(depends-on "sequential-command")
(depends-on "undo-tree")
(depends-on "yasnippet")
(depends-on "auto-complete")
(depends-on "helm")

;; vcs
(depends-on "magit")
(depends-on "git-gutter")

;; search
(depends-on "migemo")
(depends-on "anzu")
(depends-on "helm-ag")

;; by language
(depends-on "emmet-mode") ;; zencodingの後継

(depends-on "ruby-mode")
(depends-on "inf-ruby")
(depends-on "ruby-end")
(depends-on "ruby-block")
(depends-on "coffee-mode")
(depends-on "tss")
(depends-on "haml-mode")
(depends-on "sws-mode")
(depends-on "sass-mode")
(depends-on "stylus-mode")
(depends-on "yaml-mode")

(depends-on "go-mode")

(depends-on "php-mode")

(depends-on "markdown-mode")

(depends-on "elixir-mode")
